name: Generate PlantUML Diagrams
on:
  push:
    branches: [ main ] # Oder Ihr Standard-Branch-Name
    paths:
      - '**.puml'
      - '**.plantuml'

jobs:
  render:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write # Wichtig für den Schreibzugriff
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Holt die gesamte Historie für korrekte Merges

      - name: Render PlantUML
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: 'diagrams'
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Auto-Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          commit_message: "chore: update mindmap diagrams"

